/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testTestingLoop;
import javax.swing.JOptionPane;
//import java.lang.Integer;


public class App {
    public static void main(String[] args){
        int loopTimes = 0;
        while (loopTimes < 6) {

            int message = Integer.parseInt(JOptionPane.showInputDialog("Please Input Your Number : " + (loopTimes + 1))); 
            
            JOptionPane.showMessageDialog(null, message);

            loopTimes++;
        }

    }
}

